version: "3.8"
services:
    backend:
        build:
            context: ./Backend
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        environment:
            - DatabaseURL = mongodb+srv://Rafi:4ShAKvQVR58qksxc@cluster0.xyjw3s8.mongodb.net/StackOverflow?


    nginx:
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        